// start course filter section

var countryStateInfo = {
    "Australia": {
 
        "UNIVERSITY OF WOLLONGONG":["countires/australia/universities/SOUTHERN/southern.html"],
        "SAE CREATIVE MEDIA":["countires/australia/universities/sae-creative-media/sae-edu-au.html"],
        "TAYLORS COLLEGE SYDNEY":["countires/australia/universities/taylors-sydney/taylors-sydney.html"],
        "SOUTHERN CROSS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
        "CHARLES STURT UNIVERSITY MAIN CAMPUS":["countires/australia/universities/SOUTHERN/southern.html"],
        "SOUTHERN CROSS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
        "THE HOTEL SCHOOL - SYDNEY & MELBOURNE":["countires/australia/universities/SOUTHERN/southern.html"],
        "LE CORDON BLEU":["countires/australia/universities/SOUTHERN/southern.html"],
        "JAMES COOK UNIVERSITY - TOWNSVILLE & CAIRNS":["countires/australia/universities/SOUTHERN/southern.html"],
        "MACQUARIE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
        "AUSTRALIAN TECHNICAL & MANAGEMENT COLLEGE - ATMC":["countires/australia/universities/SOUTHERN/southern.html"],
        "AUSTRALIAN NATIONAL UNIVERSITY (ANU)":["countires/australia/universities/SOUTHERN/southern.html"],
        "THE UNIVERSITY OF QUEENSLAND":["countires/australia/universities/SOUTHERN/southern.html"],
        "THE UNIVERSITY OF ADELAIDE":["countires/australia/universities/SOUTHERN/southern.html"],
        "UNIVERSITY OF SOUTHERN QUEENSLAND - USQ":["countires/australia/universities/SOUTHERN/southern.html"],
        "LA TROBE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
        "EDITH COWAN UNIVERSITY (ECU)":["countires/australia/universities/SOUTHERN/southern.html"],
        "SWINBURNE UNIVERSITY OF TECHNOLOGY":["countires/australia/universities/SOUTHERN/southern.html"],
        "CQ UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
        "UNIVERSITY OF NEW ENGLAND (UNE)":["countires/australia/universities/SOUTHERN/southern.html"],
        "UNIVERSITY OF THE SUNSHINE COAST (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
        "RMIT UNIVERSITY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
        "NAVITAS - UNISMARTER MODULES":["countires/australia/universities/SOUTHERN/southern.html"],
        "LA TROBE UNIVERSITY - SYDNEY CAMPUS":["countires/australia/universities/SOUTHERN/southern.html"],
        "CURTIN COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
        "EYNESBURY":["countires/australia/universities/SOUTHERN/southern.html"],
        "LA TROBE College":["countires/australia/universities/SOUTHERN/southern.html"],
        "Deakin College":["countires/australia/universities/SOUTHERN/southern.html"],
        "NIC":["countires/australia/universities/SOUTHERN/southern.html"],
        "EDITH COWAN COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
        "SAIBT ":["countires/australia/universities/SOUTHERN/southern.html"],
        "GRIFFITH COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
        "SIBT":["countires/australia/universities/SOUTHERN/southern.html"],
        "UNIVERSITY OF CANBERRA COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
        "WESTERN SYDNEY UNIVERSITY INTERNATIONAL COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
        "UNIVERSITIES THROUGH AUSTRALIAN PARTNER":["countires/australia/universities/SOUTHERN/southern.html"],
        "Curtin University of Technology":["countires/australia/universities/SOUTHERN/southern.html"],
        "Federation University":["countires/australia/universities/SOUTHERN/southern.html"],
        "Murdoch University":["countires/australia/universities/SOUTHERN/southern.html"],
        "Swinburne University of Technology":["countires/australia/universities/SOUTHERN/southern.html"],
        "Torrens University":["countires/australia/universities/SOUTHERN/southern.html"],
        "University of Newcastle ":["countires/australia/universities/SOUTHERN/southern.html"],
        "University of Canberra":["countires/australia/universities/SOUTHERN/southern.html"],
        "University of Tasmania":["countires/australia/universities/SOUTHERN/southern.html"],
        "Queensland University of Technology - QUT":["countires/australia/universities/SOUTHERN/southern.html"],
        "University of South Australia":["countires/australia/universities/SOUTHERN/southern.html"],
        "FLYWIRE":["countires/australia/universities/SOUTHERN/southern.html"],
        "COHORT SOLUTIONS PTY LTD - COHORT GO":["countires/australia/universities/SOUTHERN/southern.html"],
        "THE UNIVERSITY OF NEWCASTLE COLLEGE OF INTERNATIONAL EDUCATION (KAPLAN)":["countires/australia/universities/SOUTHERN/southern.html"],
        "VICTORIA UNIVERSITY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
        "INTO - UNIVERSITY OF WESTERN AUSTRALIA":["countires/australia/universities/SOUTHERN/southern.html"],
        "ICHM ADELAIDE (UP EDUCATION)":["countires/australia/universities/SOUTHERN/southern.html"],

       



      },
    "Canda": {
      "VANCOUVER ISLAND UNIVERSITY": ["countires/canada/universities/vancouver-island/vancouver-island.html"],
      "UNIVERSITY OF THE FRASER VALLEY ": ["countires/canada/universities/fraser-valley/fraser-valley.html"],
      "CENTENNIAL COLLEGE": ["countires/australia/canada/centennial-college/centennial-college.html"],
      "OKANAGAN COLLEGE ":["countires/australia/universities/SOUTHERN/southern.html"],
      "CAPILANO UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "CONESTOGA COLLEGE ":["countires/australia/universities/SOUTHERN/southern.html"],
      "GEORGE BROWN COLLEGE ":["countires/australia/universities/SOUTHERN/southern.html"],
      "CAPE BRETON UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "CONFEDERATION COLLEGE ":["countires/australia/universities/SOUTHERN/southern.html"],
      "SENECA COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
      "ALGONQUIN COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"], 
"GEORGIAN COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"NIAGARA COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"FAIRLEIGH DICKINSON UNIVERSITY-FDU VANCOUVER": ["countires/australia/universities/SOUTHERN/southern.html"],
"COLUMBIA COLLEGE": ["https://www.seeriontechnologies.com/"],
"NORTH ISLAND COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"NORTHERN LIGHTS COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"BOW VALLEY COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],  
"DALHOUSIE UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"ST. CLAIR COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"], 
"FANSHAWE COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"], 
"NORTHERN COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"], 
"FRASER INTERNATIONAL COLLEGE (FIC)": ["countires/australia/universities/SOUTHERN/southern.html"],
"INTERNATIONAL COLLEGE OF MANITOBA (ICM)": ["countires/australia/universities/SOUTHERN/southern.html"],                                         
"RYERSON UNIVERSITY INTERNATIONAL COLLEGE (RUIC)": ["countires/australia/universities/SOUTHERN/southern.html"],
"WILFRID LAURIER INTERNATIONAL COLLEGE (WLIC)": ["countires/australia/universities/SOUTHERN/southern.html"],
"FLEMING COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"], 
"CAMBRIAN COLLEGE OF APPLIED ARTS & TECHNOLOGY": ["countires/australia/universities/SOUTHERN/southern.html"], 
"VANCOUVER COMMUNITY COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],  
"COLLEGE OF NEW CALEDONIA": ["countires/australia/universities/SOUTHERN/southern.html"], 
"PARKLAND COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"], 
"ROYAL ROADS UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"RED RIVER COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"SELKIRK COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"HUMBER COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"MOUNT ALLISON UNIVERSITY (UNDERGRADUATE ONLY)": ["countires/australia/universities/SOUTHERN/southern.html"],
"SHERIDAN COLLEGE INSTITUTE OF TECHNOLOGY & ADVANCED LEARNING ": ["countires/australia/universities/SOUTHERN/southern.html"],
"COLLEGE OF THE ROCKIES ": ["countires/australia/universities/SOUTHERN/southern.html"],
"KING'S UNIVERSITY COLLEGE AT WESTERN UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"STENBERG COLLEGE (SCI) AND CENTRE FOR ARTS & TECHNOLOGY (CAT)": ["countires/australia/universities/SOUTHERN/southern.html"],
"ALEXANDER COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"DURHAM COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"BROCK UNIVERSITY ": ["countires/australia/universities/SOUTHERN/southern.html"],
"ST. LAWRENCE COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"VANCOUVER FILM SCHOOL": ["countires/australia/universities/SOUTHERN/southern.html"],
"SASKATCHEWAN POLYTECHNIC ": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF SASKATCHEWAN ": ["countires/australia/universities/SOUTHERN/southern.html"],                                  
"UNIVERSITY OF MANITOBA": ["countires/australia/universities/SOUTHERN/southern.html"], 
"KWANTLEN POLYTECHNIC UNIVERSITY (KPU) ": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF WINDSOR": ["countires/australia/universities/SOUTHERN/southern.html"],
"ACADIA UNIVERSITY (UG COURSES ONLY)": ["countires/australia/universities/SOUTHERN/southern.html"],
"LOYALIST COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"LOYALIST COLLEGE - TORONTO": ["countires/australia/universities/SOUTHERN/southern.html"],
"NEW YORK INSTITUTE OF TECHNOLOGY (NYIT) - VANCOUVER": ["countires/australia/universities/SOUTHERN/southern.html"],
"OMNI COLLEGE (NURSING COURSES ONLY)": ["countires/australia/universities/SOUTHERN/southern.html"],
"CAMBRIAN @HANSON CANADA": ["countires/australia/universities/SOUTHERN/southern.html"],
"MOUNT SAINT VINCENT UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF REGINA - Graduate and UG": ["countires/australia/universities/SOUTHERN/southern.html"],
"DOUGLAS COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"CANADORE COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"LAKEHEAD UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF VICTORIA (UG ONLY)": ["countires/australia/universities/SOUTHERN/southern.html"],
"WILFRID LAURIER UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"THE UNIVERSITY OF WINNIPEG": ["countires/australia/universities/SOUTHERN/southern.html"],
"CONCORDIA UNIVERSITY OF EDMONTON ": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF WATERLOO (UG & MBET)": ["countires/australia/universities/SOUTHERN/southern.html"],
"SAULT COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF NORTHERN BRITISH COLUMBIA ": ["countires/australia/universities/SOUTHERN/southern.html"],
"MOHAWK COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"TRENT UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF LETHBRIDGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"MEDICINE HAT COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"LE CORDON BLEU": ["countires/australia/universities/SOUTHERN/southern.html"],
"ACSENDA SCHOOL OF MANAGEMENT ": ["countires/australia/universities/SOUTHERN/southern.html"],
"LAKELAND COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"YUKON UNIVERSITY ": ["countires/australia/universities/SOUTHERN/southern.html"],
"COAST MOUNTAIN COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"HERZING COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"ST. FRANCIS XAVIER UNIVERSITY ": ["countires/australia/universities/SOUTHERN/southern.html"],
"CANADIAN COLLEGE ": ["countires/australia/universities/SOUTHERN/southern.html"],
"NORTHERN COLLEGE AT PURES - TORONTO CAMPUS ": ["countires/australia/universities/SOUTHERN/southern.html"],
"YORKVILLE UNIVERSITY (UG ONLY)": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF NEW BRUNSWICK ": ["countires/australia/universities/SOUTHERN/southern.html"],
"GREAT PLAINS COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"MAPLE LEAF SCHOOLS": ["countires/australia/universities/SOUTHERN/southern.html"],
"CUMBERLAND COLLEGE, SASKATCHEWAN": ["countires/australia/universities/SOUTHERN/southern.html"],
"MACEWAN UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"LANGARA COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"BRESCIA UNIVERSITY COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"NIPISSING UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"STANFORD INTERNATIONAL COLLEGE OF BUSINESS & TECHNOLOGY": ["countires/australia/universities/SOUTHERN/southern.html"],
"BRIGHTON COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"CAMOSUN COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"LAURENTIAN UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"VANIER COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"ADLER UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"CANADIAN TOURISM COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"CEGEP MARIE-VICTORIN": ["countires/australia/universities/SOUTHERN/southern.html"],
"MATRIX COLLEGE OF MANAGEMENT, TECHNOLOGY AND HEALTHCARE INC": ["countires/australia/universities/SOUTHERN/southern.html"],
"NORTHEASTERN UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"COLLEGE MULTIHEXA": ["countires/australia/universities/SOUTHERN/southern.html"],
"CRANDALL UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"MEMORIAL UNIVERSITY OF NEWFOUNDLAND": ["countires/australia/universities/SOUTHERN/southern.html"],
"ONTARIO TECH UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"RED DEER POLYTECHNIC": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY CANADA WEST": ["countires/australia/universities/SOUTHERN/southern.html"],
"Q COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"TORONTO SCHOOL OF MANAGEMENT": ["countires/australia/universities/SOUTHERN/southern.html"],
"FLYWIRE": ["countires/australia/universities/SOUTHERN/southern.html"],
"ST. MARYS UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"TREBAS INSTITUTE": ["countires/australia/universities/SOUTHERN/southern.html"],
"NORQUEST COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"OLDS COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"BCIT": ["countires/australia/universities/SOUTHERN/southern.html"],
"ST. THOMAS UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"SOUTHERN ALBERTA INSTITUTE OF TECHNOLOGY (SAIT) ": ["countires/australia/universities/SOUTHERN/southern.html"],
"GEORGIAN@ILAC TORONTO": ["countires/australia/universities/SOUTHERN/southern.html"],
"MOUNT ROYAL UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"NIAGARA COLLEGE TORONTO": ["countires/australia/universities/SOUTHERN/southern.html"],
"WESTERN UNIVERSITY CANADA (Through EDUCO)": ["countires/australia/universities/SOUTHERN/southern.html"],
"MANITOBA INSTITUTE OF TRADES AND TECHNOLOGY (MITT)  ": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY LIVING ACCOMMODATION": ["countires/australia/universities/SOUTHERN/southern.html"],
"CANADIAN COLLEGE OF TECHNOLOGY & BUSINESS (CCTB) - VANCOUVER (THROUGH GUS)": ["countires/australia/universities/SOUTHERN/southern.html"],
"ST. CLAIR COLLEGE - ACE ACUMEN ACADEMY - TORONTO": ["countires/australia/universities/SOUTHERN/southern.html"],
"Toronto Metropolitan University - Formerly: RYERSON UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF PRINCE EDWARD ISLAND UNIVERSITY": ["countires/australia/universities/SOUTHERN/southern.html"],
"STATE BANK OF INDIA (GIC) - SBI CANADA": ["countires/australia/universities/SOUTHERN/southern.html"],
"ICICI BANK CANADA - GIC": ["countires/australia/universities/SOUTHERN/southern.html"],
"CANADIAN IMPERIAL BANK OF COMMERCE (CIBC) / SIMPLII": ["countires/australia/universities/SOUTHERN/southern.html"],
"COHORT SOLUTIONS PTY LTD - COHORT GO": ["countires/australia/universities/SOUTHERN/southern.html"],
"TAMWOOD CAREERS": ["countires/australia/universities/SOUTHERN/southern.html"],
"CODECORE COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"LASALLE COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"BISHOP'S UNIVERSITY (EDUCO)": ["countires/australia/universities/SOUTHERN/southern.html"],
"NORTH WEST COLLEGE": ["countires/australia/universities/SOUTHERN/southern.html"],
"FLEMING COLLEGE TORONTO": ["countires/australia/universities/SOUTHERN/southern.html"],
"NORTHEASTERN UNIVERSITY - TORONTO - THROUGH KAPLAN": ["countires/australia/universities/SOUTHERN/southern.html"],
 

      },
 
"Newzeland": {
      "AUT UNIVERSITY": ["countires/newzealand/universities/aut-university/aut-university.html"],
      "OTAGO POLYTECHNIC": ["countires/newzealand/universities/otago-polytechnic/otago-polytechnic.html"],
      "THE UNIVERSITY OF WAIKATO": ["countires/newzealand/universities/waikato-university/waikato-university.html"],
      "THE UNIVERSITY OF OTAGO":["countires/australia/universities/SOUTHERN/southern.html"],
      "ARA INSTITUTE OF CANTERBURY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "WINTEC & TE PUKENGA":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSAL COLLEGE OF LEARNING (UCOL)":["countires/australia/universities/SOUTHERN/southern.html"],
      "LINCOLN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UP EDUCATION ":["countires/australia/universities/SOUTHERN/southern.html"],
      "NZMA - UP EDUCATION":["countires/australia/universities/SOUTHERN/southern.html"],
	  "NEW ZEALAND SCHOOL OF TOURISM":["countires/australia/universities/SOUTHERN/southern.html"],
	  
	  "YOOBEE COLLEGES  - UP EDUCATION":["countires/australia/universities/SOUTHERN/southern.html"],
"THE CULINARY COLLECTIVE - NZMA -          UP EDUCATION":["countires/australia/universities/SOUTHERN/southern.html"],
"NEW ZEALAND INSTITUTE OF SPORT (ACG GROUP) - NZMA - UP EDUCATION":["countires/australia/universities/SOUTHERN/southern.html"],
"NEW ZEALAND COLLEGE OF MASSAGE (ACG GROUP) - NZMA - UP EDUCATION":["countires/australia/universities/SOUTHERN/southern.html"],
"AUCKLAND INSTITUTE OF STUDIES (Formerly AIS ST.HELEN’S)":["countires/australia/universities/SOUTHERN/southern.html"],
"VICTORIA UNIVERSITY OF WELLINGTON":["countires/australia/universities/SOUTHERN/southern.html"],
"MASSEY UNIVERSITY (KAPLAN)":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF AUCKLAND":["countires/australia/universities/SOUTHERN/southern.html"],
"MANUKAU INSTITUTE OF TECHNOLOGY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNITEC INSTITUTE OF TECHNOLOGY":["countires/australia/universities/SOUTHERN/southern.html"],
"WESTERN INSTITUTE OF TECHNOLOGY (WITT)":["countires/australia/universities/SOUTHERN/southern.html"],
"PACIFIC INTERNATIONAL HOTEL MANAGEMENT SCHOOL (PIHMS)":["countires/australia/universities/SOUTHERN/southern.html"],
"EASTERN INSTITUTE OF TECHNOLOGY (EIT) (No  on CCNZNP Course)":["countires/australia/universities/SOUTHERN/southern.html"],
"WELLINGTON INSTITUTE OF TECHNOLOGY (WELTEC)":["countires/australia/universities/SOUTHERN/southern.html"],
"WHITIREIA COMMUNITY POLYTECHNIC":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF CANTERBURY":["countires/australia/universities/SOUTHERN/southern.html"],
"MEDIA DESIGN SCHOOL":["countires/australia/universities/SOUTHERN/southern.html"],
"NEW ZEALAND TERTIARY COLLEGE (NZTC)":["countires/australia/universities/SOUTHERN/southern.html"],
"NELSON MARLBOROUGH INSTITUTE OF TECHNOLOGY (NMIT)":["countires/australia/universities/SOUTHERN/southern.html"],
"NEW ZEALAND SCHOOL OF EDUCATION (NZSE)":["countires/australia/universities/SOUTHERN/southern.html"],
"QUEENSTOWN RESORT COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
"NEW ZEALAND INSTITUTE OF EDUCATION (NZIE)":["countires/australia/universities/SOUTHERN/southern.html"],
"ASPIRE2 INTERNATIONAL - NTEC TERTIARY GROUP":["countires/australia/universities/SOUTHERN/southern.html"],
                                          
"TOI-OHOMAI & TE PUKENGA":["countires/australia/universities/SOUTHERN/southern.html"],
"NAVITAS - UCIC":["countires/australia/universities/SOUTHERN/southern.html"],
"SOUTHERN INSTITUTE OF TECHNOLOGY":["countires/australia/universities/SOUTHERN/southern.html"],
"NORTHLAND POLYTECHNIC (NORTHTEC)":["countires/australia/universities/SOUTHERN/southern.html"],
"INTERNATIONAL TRAVEL COLLEGE (ITC) OF NEW ZEALAND":["countires/australia/universities/SOUTHERN/southern.html"],
"WHITECLIFFE COLLEGE ":["countires/australia/universities/SOUTHERN/southern.html"],
"NEW ZEALAND INSTITUTE OF BUSINESS & TECHNOLOGY (NZIBT)":["countires/australia/universities/SOUTHERN/southern.html"], 
"FLYWIRE":["countires/australia/universities/SOUTHERN/southern.html"],
"COHORT SOLUTIONS PTY LTD - COHORT GO":["countires/australia/universities/SOUTHERN/southern.html"], 


 
      },
  "United Kingdom": {
      "ANGLIA RUSKIN UNIVERSITY ": ["countires/uk/universities/anglia-ruskin/anglia-ruskin.html"],
      "THE ROBERT GORDON UNIVERSITY – ABERDEEN, SCOTLAND ": ["countires/uk/universities/robert-gordon/robert-gordon.html"],
      "BIRMINGHAM CITY UNIVERSITY":["countires/uk/universities/birmingham/birmingham.html"],
      "UNIVERSITY OF DERBY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF WOLVERHAMPTON":["countires/australia/universities/SOUTHERN/southern.html"],
    "LONDON SOUTH BANK UNIVERSITY (LSBU)":["countires/australia/universities/SOUTHERN/southern.html"],
       "UNIVERSITY OF LINCOLN ":["countires/australia/universities/SOUTHERN/southern.html"],
        "UNIVERSITY OF STIRLING - SCOTLAND":["countires/australia/universities/SOUTHERN/southern.html"],
        "ROEHAMPTON UNIVERSITY – LONDON":["countires/australia/universities/SOUTHERN/southern.html"],
        "NEWCASTLE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
		"UNIVERSITY OF ESSEX":["countires/australia/universities/SOUTHERN/southern.html"], 
"UNIVERSITY OF PORTSMOUTH":["countires/australia/universities/SOUTHERN/southern.html"],
"BOURNEMOUTH UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"GLASGOW CALEDONIAN UNIVERSITY":["https://www.bbc.com/"],
"ABERYSTWYTH UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF SURREY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF SUNDERLAND":["countires/australia/universities/SOUTHERN/southern.html"],
"SWANSEA UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF BRADFORD":["countires/australia/universities/SOUTHERN/southern.html"],
"MIDDLESEX UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF SALFORD ":["countires/australia/universities/SOUTHERN/southern.html"],
"THE UNIVERSITY OF SOUTH WALES ":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF BRIGHTON":["countires/australia/universities/SOUTHERN/southern.html"],
"LIVERPOOL JOHN MOORES UNIVERSITY (LJMU)":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF CHESTER":["countires/australia/universities/SOUTHERN/southern.html"],
"COVENTRY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"BATH SPA UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF GLOUCESTERSHIRE ":["countires/australia/universities/SOUTHERN/southern.html"],                      
"TEESSIDE UNIVERSITY - No  for applications from Punjab":["countires/australia/universities/SOUTHERN/southern.html"],
"CARDIFF METROPOLITAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
"UNIVERSITY OF EAST ANGLIA":["countires/australia/universities/SOUTHERN/southern.html"],
"CITY UNIVERSITY LONDON":["countires/australia/universities/SOUTHERN/southern.html"], 
"BRUNEL UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF EXETER":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF CENTRAL LANCASHIRE (UCLAN)":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF BEDFORDSHIRE":["countires/australia/universities/SOUTHERN/southern.html"],
"HERIOT-WATT UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF STRATHCLYDE":["countires/australia/universities/SOUTHERN/southern.html"],
"EDINBURGH NAPIER UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF DUNDEE":["countires/australia/universities/SOUTHERN/southern.html"],
"BIRKBECK, UNIVERSITY OF LONDON":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF SOUTHAMPTON":["countires/australia/universities/SOUTHERN/southern.html"],
"ABERTAY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"CRANFIELD UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF KENT":["countires/australia/universities/SOUTHERN/southern.html"],
"LEEDS BECKETT UNIVERSITY   ":["countires/australia/universities/SOUTHERN/southern.html"],      
"Formerly LEEDS METROPOLITAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],             
"QUEEN MARGARET UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"THE UNIVERSITY OF READING":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF THE WEST OF SCOTLAND":["countires/australia/universities/SOUTHERN/southern.html"],                                                  
"UNIVERSITY OF CHICHESTER":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF PLYMOUTH":["countires/australia/universities/SOUTHERN/southern.html"],
"BANGOR UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"LIVERPOOL HOPE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF THE WEST OF ENGLAND":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF WESTMINSTER":["countires/australia/universities/SOUTHERN/southern.html"],
"OXFORD BROOKES UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"QUEEN MARY, UNIVERSITY OF LONDON":["countires/australia/universities/SOUTHERN/southern.html"], 
"UNIVERSITY OF GREENWICH ":["countires/australia/universities/SOUTHERN/southern.html"],                                                                          
"MANCHESTER METROPOLITAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"STAFFORDSHIRE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF ABERDEEN":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF EAST LONDON":["countires/australia/universities/SOUTHERN/southern.html"],
"KEELE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"LOUGHBOROUGH UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF LIVERPOOL":["countires/australia/universities/SOUTHERN/southern.html"],                                                           
"UNIVERSITY OF LEEDS":["countires/australia/universities/SOUTHERN/southern.html"],
"ARTS UNIVERSITY BOURNEMOUTH":["countires/australia/universities/SOUTHERN/southern.html"],
"SHEFFIELD HALLAM UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"DE MONTFORT UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],                                                                    
"UNIVERSITY OF HUDDERSFIELD":["countires/australia/universities/SOUTHERN/southern.html"],
"ULSTER UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"SOLENT UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"NOTTINGHAM TRENT UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UAL SHORT COURSES LIMITED":["countires/australia/universities/SOUTHERN/southern.html"],        
"ROYAL AGRICULTURAL UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF BRISTOL":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF YORK":["countires/australia/universities/SOUTHERN/southern.html"],
"NAVITAS COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
"BCUIC":["countires/australia/universities/SOUTHERN/southern.html"],
"UPIC":["countires/australia/universities/SOUTHERN/southern.html"],
"HIC, The College Swansea University, ICP, ICRGU":["countires/australia/universities/SOUTHERN/southern.html"],
"HIC, BULPC, CRIC, ICP, UPIC, ICRGU, BCUIC, UNIC, The College Swansea University":["countires/australia/universities/SOUTHERN/southern.html"],
"HIC":["countires/australia/universities/SOUTHERN/southern.html"],
"BULPC, CRIC, ICP, UPIC, ICRGU, BCUIC, UNIC, The College Swansea University":["countires/australia/universities/SOUTHERN/southern.html"],
"HIC":["countires/australia/universities/SOUTHERN/southern.html"],
"BULPC, CRIC, ICP, UPIC, ICRGU, BCUIC, UNIC, The College Swansea University":["countires/australia/universities/SOUTHERN/southern.html"],
"NAVITAS - UNISMARTER MODULES":["countires/australia/universities/SOUTHERN/southern.html"],
"NAVITAS - FOLLOW-ON  FROM UK PARTNER INSTITUTIONS":["countires/australia/universities/SOUTHERN/southern.html"],
"NAVITAS COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
"BCUIC":["countires/australia/universities/SOUTHERN/southern.html"],
"CRIC":["countires/australia/universities/SOUTHERN/southern.html"],
"HIC":["countires/australia/universities/SOUTHERN/southern.html"],
"ICP":["countires/australia/universities/SOUTHERN/southern.html"],
"ICRGU":["countires/australia/universities/SOUTHERN/southern.html"],
"The College, Swansea University":["countires/australia/universities/SOUTHERN/southern.html"],
"BULPC":["countires/australia/universities/SOUTHERN/southern.html"],
"UPIC":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIC":["countires/australia/universities/SOUTHERN/southern.html"],
"LEICESTER GLOBAL STUDY CENTRE - UNIVERSITY OF LEICESTER":["countires/australia/universities/SOUTHERN/southern.html"],
"INTO - UK ":["countires/australia/universities/SOUTHERN/southern.html"],                                                                                    
"UNIVERSITY OF EAST ANGLIA":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF EXETER":["countires/australia/universities/SOUTHERN/southern.html"],
"NEWCASTLE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"QUEEN’S UNIVERSITY BELFAST":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF STIRLING":["countires/australia/universities/SOUTHERN/southern.html"],
"STUDY GROUP – INTERNATIONAL STUDY CENTRE (ISC)":["countires/australia/universities/SOUTHERN/southern.html"], 
"GLASGOW SCHOOL OF ART":["countires/australia/universities/SOUTHERN/southern.html"],
"ONCAMPUS-UK CAMBRIDGE EDUCATION GROUP (CEG)":["countires/australia/universities/SOUTHERN/southern.html"],
"KAPLAN - UK - KAPLAN INTERNATIONAL COLLEGES":["countires/australia/universities/SOUTHERN/southern.html"],
"University of Birmingham":["countires/australia/universities/SOUTHERN/southern.html"],
"University of Nottingham":["countires/australia/universities/SOUTHERN/southern.html"],
"University of York":["countires/australia/universities/SOUTHERN/southern.html"],
"University of Glasgow":["countires/australia/universities/SOUTHERN/southern.html"],
"Aston University":["countires/australia/universities/SOUTHERN/southern.html"],
"Cranfield University":["countires/australia/universities/SOUTHERN/southern.html"],
"City University":["countires/australia/universities/SOUTHERN/southern.html"],
"University of Liverpool":["countires/australia/universities/SOUTHERN/southern.html"],
"University of Westminster":["countires/australia/universities/SOUTHERN/southern.html"],
"University of West of England - Bristol":["countires/australia/universities/SOUTHERN/southern.html"],
"Bournemouth University":["countires/australia/universities/SOUTHERN/southern.html"],
"University of Brighton":["countires/australia/universities/SOUTHERN/southern.html"],
"Nottingham Trent University ":["countires/australia/universities/SOUTHERN/southern.html"],                                                                     
"AMITY GLOBAL BUSINESS SCHOOL LONDON":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY COLLEGE BIRMINGHAM":["countires/australia/universities/SOUTHERN/southern.html"],
"EUROPEAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"LE CORDON BLEU":["countires/australia/universities/SOUTHERN/southern.html"],
"REGENT'S UNIVERSITY LONDON":["countires/australia/universities/SOUTHERN/southern.html"],
"QA HIGHER EDUCATION (QAHE)":["countires/australia/universities/SOUTHERN/southern.html"], 
"THE UNIVERSITY OF NOTTINGHAM":["countires/australia/universities/SOUTHERN/southern.html"],
"ASTON UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF WEST LONDON":["countires/australia/universities/SOUTHERN/southern.html"],
"THE UNIVERSITY OF SHEFFIELD":["countires/australia/universities/SOUTHERN/southern.html"],
"CANTERBURY CHRIST CHURCH UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],                        
"DURHAM UNIVERSIY":["countires/australia/universities/SOUTHERN/southern.html"],
"ISTITUTO MARANGONI":["countires/australia/universities/SOUTHERN/southern.html"],
"KINGSTON UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"], 
"FALMOUTH UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"FLYWIRE":["countires/australia/universities/SOUTHERN/southern.html"],
"RAVENSBOURNE UNIVERSITY LONDON":["countires/australia/universities/SOUTHERN/southern.html"], 
"UNIVERSITY FOR THE CREATIVE ARTS":["countires/australia/universities/SOUTHERN/southern.html"],
"UNILODGERS (ACCOMMODATION)":["countires/australia/universities/SOUTHERN/southern.html"],
"NORWICH UNIVERSITY OF THE ARTS":["countires/australia/universities/SOUTHERN/southern.html"],
"BISHOP GROSSETESTE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"LEEDS ARTS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY LIVING ACCOMMODATION":["countires/australia/universities/SOUTHERN/southern.html"],
"COHORT SOLUTIONS PTY LTD - COHORT GO":["countires/australia/universities/SOUTHERN/southern.html"],
"ARDEN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
"UNIVERSITY OF SUSSEX":["countires/australia/universities/SOUTHERN/southern.html"],
"ST. MARY'S UNIVERSITY, TWICKENHAM":["countires/australia/universities/SOUTHERN/southern.html"],
"KAPLAN OPEN LEARNI ":["countires/australia/universities/SOUTHERN/southern.html"],      
 
  },
    "USA": {
      "NORTHWEST MISSOURI STATE UNIVERSITY":["countires/usa/universities/northwest-missouri/northwest-missouri.html"],
      "DALLAS BAPTIST UNIVERSITY":["countires/usa/universities/dallas-baptist/dallas-baptist.html"],
      "DRURY UNIVERSITY (UNDERGRADUATE ONLY)":["countires/usa/universities/drury-university/drury-university.html"],
      "NEWMAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "TROY UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "SOUTHEAST MISSOURI STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WICHITA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF CALIFORNIA, EXTENSION, RIVERSIDE (INTERNATIONAL EDUCATION PROGRAMS)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF WISCONSIN - EAU CLAIRE":["countires/australia/universities/SOUTHERN/southern.html"],
      "ROCHESTER INSTITUTE OF TECHNOLOGY (RIT)":["countires/australia/universities/SOUTHERN/southern.html"],
	  
	  
      "LIBERTY UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "SOUTHERN NEW HAMPSHIRE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "KENT STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "AUBURN UNIVERSITY AT MONTGOMERY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SAINT PETER'S UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SACRED HEART UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF WISCONSIN-STOUT":["countires/australia/universities/SOUTHERN/southern.html"],
      "NEW YORK INSTITUTE OF TECHNOLOGY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "CLEVELAND STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "FRESNO STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF MICHIGAN":["countires/australia/universities/SOUTHERN/southern.html"],
      "INTO - USA":["countires/australia/universities/SOUTHERN/southern.html"],
      "OREGON STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "UNIVERSITY OF SOUTH FLORIDA":["countires/australia/universities/SOUTHERN/southern.html"], 
      "COLORADO STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "MARSHALL UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "GEORGE MASON UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "SAINT LOUIS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "DREW UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],                                                                        
      "INTO - USA - UNIVERSITY OF ARIZONALONG ISLAND":["countires/australia/universities/SOUTHERN/southern.html"],
      "GANNON UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "HUMBOLDT STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY, STANISLAUS":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA LUTHERAN UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF NEW MEXICO":["countires/australia/universities/SOUTHERN/southern.html"],
      "PACIFIC LUTHERAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NORTH TEXAS":["countires/australia/universities/SOUTHERN/southern.html"],  
       "DEVRY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF CALIFORNIA":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "NEW YORK FILM ACADEMY":["countires/australia/universities/SOUTHERN/southern.html"],
      "FULL SAIL UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WESTERN KENTUCKY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "FLORIDA INTERNATIONAL UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "ASHLAND UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SANTA BARBARA CITY COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
      "BERKELEY COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],  
      "NEW YORK and NEW JERSEY":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE CULINARY INSTITUTE OF AMERICA":["countires/australia/universities/SOUTHERN/southern.html"],  
      "FONTBONNE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SAGINAW VALLEY STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "PITTSBURG STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NEVADA":["countires/australia/universities/SOUTHERN/southern.html"],
      "OHIO WESLEYAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF CINCINNATI":["countires/australia/universities/SOUTHERN/southern.html"],
      "DAKOTA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NEW HAVEN":["countires/australia/universities/SOUTHERN/southern.html"],
      "MONTANA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "TENNESSEE TECH UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "UPPER IOWA UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "NORTHERN ARIZONA UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "NORTHEASTERN UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],                                                              
      "PACE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WILLIAM CAREY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "GOLDEN GATE UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "JACKSONVILLE STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "NAVITAS - USA ":["countires/australia/universities/SOUTHERN/southern.html"],
      "FAU, UMASS Boston":["countires/australia/universities/SOUTHERN/southern.html"],
      " FAU":["countires/australia/universities/SOUTHERN/southern.html"],
      "UMASS Boston, FAU":["countires/australia/universities/SOUTHERN/southern.html"],
      "UMASS Boston, FAU":["countires/australia/universities/SOUTHERN/southern.html"],
      "UMASS Boston, FAU":["countires/australia/universities/SOUTHERN/southern.html"],
      "NAVITAS USA":["countires/australia/universities/SOUTHERN/southern.html"],
      "FAU":["countires/australia/universities/SOUTHERN/southern.html"],
      "UMB":["countires/australia/universities/SOUTHERN/southern.html"],
      "RBC":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY FULTON-MONTGOMERY COMMUNITY COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
      "AUSTIN PEAY STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF TAMPA":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF COLORADO":["countires/australia/universities/SOUTHERN/southern.html"],
      "TIFFIN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "EASTERN KENTUCKY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY BRIDGE":["countires/australia/universities/SOUTHERN/southern.html"],
      "SANTIAGO CANYON COLLEGE, CALIFORNIA":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF DELAWARE":["countires/australia/universities/SOUTHERN/southern.html"], 
      "MISSISSIPPI STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "STUDY GROUP USA":["countires/australia/universities/SOUTHERN/southern.html"],
      "BAYLOR UNIVERSITY (GRAGUATE & UG)":["countires/australia/universities/SOUTHERN/southern.html"],
       "DEPAUL UNIVERSITY (GRADUATE & UG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "JAMES MADISON UNIVERSITY  ":["countires/australia/universities/SOUTHERN/southern.html"],
      "LIPSCOMB UNIVERSITY (UG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "TEXAS A&M UNIVERSITY - CORPUS CHRISTI (GRADUATE & UG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "WESTERN WASHINGTON UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF HARTFORD":["countires/australia/universities/SOUTHERN/southern.html"],
      "FLORIDA ATLANTIC UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "KAPLAN - USA":["countires/australia/universities/SOUTHERN/southern.html"],
      "PACE UNIVERSITY  ":["countires/australia/universities/SOUTHERN/southern.html"],                 
      "THE UNIVERSITY OF TULSA":["countires/australia/universities/SOUTHERN/southern.html"],
      "ARIZONA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"], 
      "UNIVERSITY OF CONNECTICUT":["countires/australia/universities/SOUTHERN/southern.html"],
      "SIMMONS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "INDIANA TECH (INDIANA INSTITUTE OF TECHNOLOGY)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF MOUNT UNION":["countires/australia/universities/SOUTHERN/southern.html"],
      "HIGH POINT UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UCLA EXTENSION":["countires/australia/universities/SOUTHERN/southern.html"],
      "NORTHEASTERN ILLINOIS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY GENESEO":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF INDIANAPOLIS":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF ST. FRANCIS":["countires/australia/universities/SOUTHERN/southern.html"],
      "LAWRENCE TECHNOLOGICAL UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SAN JOSE STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "NEW ENGLAND INSTITUTE OF TECHNOLOGY":["countires/australia/universities/SOUTHERN/southern.html"],
      "OHIO DOMINICAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF MAINE, ORONO":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF TENNESSEE":["countires/australia/universities/SOUTHERN/southern.html"],
      "SAN FRANCISCO STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "MURRAY STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WESTERN ILLINOIS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "COLUMBUS STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF MARY HARDIN-BAYLOR":["countires/australia/universities/SOUTHERN/southern.html"],
      "NORTHERN KENTUCKY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SHORELIGHT - USA":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF KANSAS - UG":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF CENTRAL FLORIDA - UG":["countires/australia/universities/SOUTHERN/southern.html"], 
      "LOUSIANA STATE UNIVERSITY - UG ":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF SOUTH CAROLINA - UG & PG":["countires/australia/universities/SOUTHERN/southern.html"],
      "ADELPHI UNIVERSITY - UG, PG, MBA":["countires/australia/universities/SOUTHERN/southern.html"], 
      "AMERICAN UNIVERSITY - UG, PG and MAP":["countires/australia/universities/SOUTHERN/southern.html"], 
      "AUBURN UNIVERSITY - UG, PG and MAP ":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF THE PACIFIC - UG Pathway, DIRECT ENTRY UG, PG, and MAP":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF ILLINOIS AT CHICAGO (UG and PG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF DAYTON (PG and UG - Direct entry)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UMASS BOSTON (UG and PG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UMASS AMHERST (PG) ":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF UTAH (UG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "CLEVELAND STATE UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF MISSISSIPPI (UG and PG) ":["countires/australia/universities/SOUTHERN/southern.html"],
      "SOUTHWESTERN UNIVERSITY - UG ":["countires/australia/universities/SOUTHERN/southern.html"],
      "GONZAGA UNIVERSITY - UG and PG ":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF LYNCHBURG - UG and PG":["countires/australia/universities/SOUTHERN/southern.html"],
      "WESTERN OREGON UNIVERSITY (UG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "OLD DOMINION UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "OHIO UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "NORTHWOOD UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF SOUTHERN MAINE":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY NEW PALTZ":["countires/australia/universities/SOUTHERN/southern.html"],
      "SOUTHERN ILLINOIS UNIVERSITY EDWARDSVILLE":["countires/australia/universities/SOUTHERN/southern.html"],
      "NORTHEASTERN STATE UNIVERSITY, OKLAHOMA ":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF WISCONSIN-LA CROSSE ":["countires/australia/universities/SOUTHERN/southern.html"],
      "FERRIS STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SONOMA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NORTH CAROLINA AT WILMINGTON ":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY OSWEGO":["countires/australia/universities/SOUTHERN/southern.html"],
      "MCPHS UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "NORTH PARK UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "YOUNGSTOWN STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WESTERN NEW ENGLAND UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "ROBERT MORRIS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUFFOLK UNIVERSITY BOSTON":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA BAPTIST UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF MEMPHIS":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF ALABAMA,":["countires/australia/universities/SOUTHERN/southern.html"],                                   
      "UNIVERSITY OF CENTRAL OKLAHOMA":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF MARYLAND":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NEBRASKA":["countires/australia/universities/SOUTHERN/southern.html"],
      "DUKE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "DUQUESNE UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "SEATTLE PACIFIC UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "STEVENS INSTITUTE OF TECHNOLOGY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "BRENAU UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "EMBRY-RIDDLE AERONAUTICAL UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "JACKSONVILLE UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "LASELL UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "RADFORD UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "ROWAN UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "GEORGIAN COURT UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "ARKANSAS STATE UNIVERSITY, JONESBORO (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
     "CAPITAL UNIVERSITY  (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
     "EAST TENNESSEE STATE UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "FLORIDA A&M UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "RIVIER UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NORTH ALABAMA (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF TOLEDO (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "WILKES UNIVERSITY (EDUCO) - Application should be sent to GeeBee only":["countires/australia/universities/SOUTHERN/southern.html"],
      "TEXAS TECH UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WESTFIELD STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WRIGHT STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF TENNESSEE, CHATTANOOGA":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF FINDLAY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF CENTRAL MISSOURI":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY, CHANNEL ISLANDS":["countires/australia/universities/SOUTHERN/southern.html"],
      "MONTANA STATE UNIVERSITY-BILLINGS":["countires/australia/universities/SOUTHERN/southern.html"],
      "ST. GEORGE'S UNIVERSITY, GRENADA, WEST INDIES":["countires/australia/universities/SOUTHERN/southern.html"],
      "MOREHEAD STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY POLYTECHNIC INSTITUTE (SUNYIT)":["countires/australia/universities/SOUTHERN/southern.html"],
      "TEXAS WESLEYAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "PURDUE UNIVERSITY FORT WAYNE":["countires/australia/universities/SOUTHERN/southern.html"],
      "MARYMOUNT UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "OKLAHOMA CITY UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "WILMINGTON UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "IOWA WESLEYAN UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY BUFFALO STATE COLLEGE":["countires/australia/universities/SOUTHERN/southern.html"],
      "SAINT LEO UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF CHARLESTON":["countires/australia/universities/SOUTHERN/southern.html"],
      "CONCORDIA UNIVERSITY, NEBRASKA":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF NORTH CAROLINA, GREENSBORO ":["countires/australia/universities/SOUTHERN/southern.html"],
      "CLAREMONT GRADUATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "VALPARAISO UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "SOUTHERN CONNECTICUT STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY, SACRAMENTO":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF DETROIT MERCY":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY,  LONG BEACH":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY - THE COLLEGE AT BROCKPORT":["countires/australia/universities/SOUTHERN/southern.html"],
      "MCNEESE STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF MISSOURI - ST. LOUIS":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY, FULLERTON":["countires/australia/universities/SOUTHERN/southern.html"],
      "MIDDLE TENNESSEE STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "COLLEGE OF STATEN ISLAND, CITY UNIVERSITY OF NEW YORK":["countires/australia/universities/SOUTHERN/southern.html"],
      "SUNY, UNIVERSITY AT ALBANY":["countires/australia/universities/SOUTHERN/southern.html"],
      "FLYWIRE":["countires/australia/universities/SOUTHERN/southern.html"],
      "CALIFORNIA STATE UNIVERSITY, EAST BAY":["countires/australia/universities/SOUTHERN/southern.html"],
      "MISSOURI UNIVERSITY OF SCIENCE & TECHNOLOGY - MISSOURI S&T":["countires/australia/universities/SOUTHERN/southern.html"],
      "WASHINGTON STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "DEPAUL UNIVERSITY - DIRECT TIE-UP":["countires/australia/universities/SOUTHERN/southern.html"],
      "WEBSTER UNIVERSITY (THROUGH GUS)":["countires/australia/universities/SOUTHERN/southern.html"],
      "CONCORDIA UNIVERSITY CHICAGO (THROUGH GUS)":["countires/australia/universities/SOUTHERN/southern.html"],
      "FLORIDA POLYTECHNIC UNIVERSITY (THROUGH GUS)":["countires/australia/universities/SOUTHERN/southern.html"],
      "HERZING UNIVERSITY (THROUGH GUS)":["countires/australia/universities/SOUTHERN/southern.html"],
      "NEW JERSEY INSTITUTE OF TECHNOLOGY (NJIT)":["countires/australia/universities/SOUTHERN/southern.html"],
      "SAN DIEGO STATE UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY LIVING ACCOMMODATION":["countires/australia/universities/SOUTHERN/southern.html"],
      "CASTLETON UNIVERSITY (Through Square) ":["countires/australia/universities/SOUTHERN/southern.html"],
      "HAWAII PACIFIC UNIVERSITY (Through Msquare)":["countires/australia/universities/SOUTHERN/southern.html"],
      "CHRISTIAN BROTHERS UNIVERSITY":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF HOUSTON - CLEAR LAKE":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNILODGERS (ACCOMMODATION)":["countires/australia/universities/SOUTHERN/southern.html"],
      "COHORT SOLUTIONS PTY LTD - COHORT GO":["countires/australia/universities/SOUTHERN/southern.html"],
      "THE UNIVERSITY OF SCRANTON":["countires/australia/universities/SOUTHERN/southern.html"],
      "OUTLEAP TECHNOLOGIES PRIVATE LTD - EDUCATION LOAN":["countires/australia/universities/SOUTHERN/southern.html"],
      "COLLEGE OF THE CANYONS (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "CREIGHTON UNIVERSITY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "ROSE-HULMAN  INSTITUTE OF TECHNOLOGY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "SALEM UNIVERSITY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "TRINE UNIVERSITY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF WEST ALABAMA (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF WEST FLORIDA (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "ONESTEP GLOBAL - ETS - TOEFL":["countires/australia/universities/SOUTHERN/southern.html"],
      "CONCORD UNIVERSITY -  THROUGH ENROLLMENT ADVISORY GROUP (EAG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "MANHATTAN COLLEGE - THROUGH ENROLLMENT ADVISORY GROUP (EAG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "NOVA SOUTHEASTERN UNIVERSITY - THROUGH ENROLLMENT ADVISORY GROUP (EAG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF BRIDGEPORT THROUGH ENROLLMENT ADVISORY GROUP (EAG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NEBRASKA AT KEARNEY - THROUGH ENROLLMENT ADVISORY GROUP (EAG)":["countires/australia/universities/SOUTHERN/southern.html"],
      "HDFC CREDILA":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF NEVADA, LAS VEGAS (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF TULSA (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "YESHIVA UNIVERSITY ":["countires/australia/universities/SOUTHERN/southern.html"],
      "CAMPBELLSVILLE UNIVERSITY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "MIDWESTERN STATE UNIVERSITY (EDUCO)":["countires/australia/universities/SOUTHERN/southern.html"],
      "UNIVERSITY OF COLORADO (SPRINGS)":["countires/australia/universities/SOUTHERN/southern.html"],
 
  }
  
}



window.onload = function () {
  //Get html elements
  let country_sel = document.getElementById("country_sel");
  let university_sel = document.getElementById("university_sel");
 
  //Load countries
  for (let country in countryStateInfo) {
      country_sel.options[country_sel.options.length] = new Option(country, country);
  }
  //County Changed
  country_sel.onchange = function () {
       university_sel.length = 1; // remove all options bar first
       if (this.selectedIndex < 1)
           return; // done

       for (let state in countryStateInfo[this.value]) {
           university_sel.options[university_sel.options.length] = new Option(state, countryStateInfo[this.value][state]);
       }
  }
} 

$(document).ready(function(){
  $("#filter_s").click(function () {
      if($("#university_sel option:selected").val() !== ""){
          window.location.href = $("#university_sel").val(); 
      }
  })
})

// end of the course filters